version: "3.8"

services:
  db:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules
    ports: 
      - 5000:3000
    command: npm run start:debug

  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    ports: 
      - 3000:3000
    command: npm run dev

volumes:
  dbdata: