version: "3.8"

services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules
    ports: 
      - 5000:3000
    command: npm run start:dev

  frontend:
    build: 
      context: ./frontend
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    ports: 
      - 3000:3000
    command: npm run dev